### PR TITLE
Style/windows xp

### PR DESCRIPTION
**Pull request by cashd932**
Made a windows-xp looking base style and cleaned up the css. Give it a look, I'm sure we'll iterate on the specifics of the styles, but hopefully this is better than what we've been working with,

### CODE REVIEW

**Comment by baileysingleton** [comment]
Lol windows xp

**Comment by cashd932** [comment]
It is though
localhost_8080 - google chrome 2017-10-26 20 02 38

**Comment by danvanhorn** [comment]
Green?

**Comment by danvanhorn** [comment]
#39 #33

**Pull request merged**
